[memory][sc-fs-storage][sc-dictionary] Fix memory leak, add prefix removing in sc-dictionary destroy
ostis-ai/sc-machine pull request #102
Opened 2022-07-09 10:15 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)

2022-07-12 08:06 UTC, KovalM requested changes

2022-07-12 08:38 UTC, NikitaZotov commented on sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c
> +  sc_mem_free(hash_str);
I didn't notice it. Thanks

2022-07-12 20:10 UTC, KovalM approved these changes

2022-07-22 14:34 UTC, AlexandrZagorskiy approved these changes

2022-07-25 11:06 UTC, VasKho approved these changes
Looks good to me

2022-07-25 14:31 UTC, merged