Write sc-machine idea in readme
ostis-ai/sc-machine pull request #120
Opened 2022-08-04 21:06 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [ ] Update documentation

2022-08-05 09:31 UTC, MksmOrlov commented on README.md
> +(programs, modules, systems, communication between systems) knowledge represents on one language, named as SC-code.
```suggestion
(programs, modules, systems, communication between systems) knowledge represents on the same language, named as SC-code. 
```

2022-08-05 09:32 UTC, MksmOrlov commented on README.md
> +- semantic storage to store graph constructions, named as sc-memory (graph database);
```suggestion
- semantic storage to store graph constructions, named sc-memory (graph database);
```

2022-08-05 09:36 UTC, MksmOrlov commented on README.md
> +   - <u>network</u> program API, provided by <i>sc-server</i> to communicate with storage by network with help of Websocket
I think "program" is redundant

2022-08-05 09:39 UTC, MksmOrlov commented on README.md
> +way of one technology</u>, <u>one data representation and programming language</u> and <u>one program software</u>!
It seems that u tag doesn't work. Chack all over the document

2022-08-05 09:46 UTC, MksmOrlov commented on README.md
> +Sc-machine is a part of the whole system, named as <b>OSTIS Web platform</b>.
What do you mean by "whole system"? I think it is better to say that sc-machine is a core for an ostis-system. OSTIS Web Platform is an example of one

2022-08-05 09:48 UTC, MksmOrlov commented on README.md
> +[write issue](https://github.com/ostis-ai/sc-machine/issues) to OSTIS-web-platform developers.
Why this line is in Docker section?

2022-08-05 10:24 UTC, MksmOrlov approved these changes

2022-08-05 10:24 UTC, MksmOrlov commented on README.md
> +way of one technology***, ***one data representation and programming language*** and ***one program software***!
I am not sure that "one" is correct word here. Maybe "the same" or smth like that

2022-08-08 13:23 UTC, AlexandrZagorskiy requested changes

2022-08-08 13:23 UTC, AlexandrZagorskiy commented on README.md
> +SC-machine provide complete and sufficient native and network APIs to create, update, delete and retrieve operations and
```suggestion
SC-machine provide complete and sufficient native and network APIs to create, retrieve, update and delete  operations and
```

2022-08-08 13:23 UTC, AlexandrZagorskiy commented on README.md
> +Start use [OSTIS-web-platform](https://github.com/ostis-ai/ostis-standard) to integrate all the world solutions ***by the
```suggestion
Start use [OSTIS-web-platform](https://github.com/ostis-ai/ostis-web-platform) to integrate all the world solutions ***by the 
```

2022-08-08 14:40 UTC, MksmOrlov commented on README.md
> +SC-machine provide complete and sufficient native and network APIs to create, update, delete and retrieve operations and
why?

2022-08-09 20:20 UTC, AlexandrZagorskiy approved these changes

2022-08-15 06:46 UTC, merged