[docs] Replace latex docs with new macros
ostis-ai/sc-machine pull request #148
Opened 2022-09-11 19:38 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [ ] Update documentation

2022-09-12 09:10 UTC, VasKho requested changes
We don't have following commands in `scn-latex-plugin`
```TeX
\scnexplanation
\scnnote
\begin{scnsubdividing} % i.e. environment
```
If you're really would like to use you should define this commands in main file or simply replace them with `\scnrelfrom{пояснение}`, `\scnrelfrom{примечание}`, `\begin{scnrelfromset}{разбиение}` respectively.

2022-09-20 19:10 UTC, KovalM requested changes
Add scn-latex-plugin of detected version as submodule and add instruction how to compile docs localy

2022-09-21 14:25 UTC, VasKho approved these changes

2022-09-21 14:37 UTC, KovalM approved these changes

2022-09-22 21:08 UTC, merged