[doc] Add contributing rules
ostis-ai/sc-machine pull request #151
Opened 2022-09-11 20:30 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [ ] Update documentation

2022-09-12 07:01 UTC, AlexandrZagorskiy requested changes
Looks like file should be refactored. Commit examples, Pull Request section, etc.
![image](https://user-images.githubusercontent.com/34061914/189591482-5d416117-ddb5-4b99-8157-4e8d768b525b.png)

2022-09-12 18:50 UTC, KovalM requested changes

2022-09-12 18:50 UTC, KovalM commented on docs/index.md
> +    * [Pull Request](../CONTRIBUTING.md)
We need to delete dev/pr for support these rules in single place

2022-09-12 18:50 UTC, KovalM commented on CONTRIBUTING.md
> +[cpp] Colored log output
Revert formatting from dev/pr.md

2022-09-12 18:50 UTC, KovalM commented on CONTRIBUTING.md
> +### After Pull Request Review
Not all contributes can do it

2022-09-15 09:12 UTC, AlexandrZagorskiy approved these changes

2022-09-15 12:21 UTC, KovalM requested changes

2022-09-15 12:21 UTC, KovalM commented on CONTRIBUTING.md
> +### After Pull Request Review
Not fixed

2022-09-19 12:10 UTC, merged