[ci] Add ci for ubuntu 22.04
ostis-ai/sc-machine pull request #170
Opened 2022-09-23 11:56 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [ ] Update documentation

2022-09-23 15:43 UTC, KovalM requested changes

2022-09-23 15:43 UTC, KovalM commented on sc-tools/sc-config-utils/sc-config/sc_config.hpp
> +#include <typeinfo>
```suggestion

#include <typeinfo>
```

2022-09-25 17:02 UTC, NikitaZotov commented
This PR solved bug issue https://github.com/ostis-ai/sc-machine/issues/33

2022-09-27 17:09 UTC, NikitaZotov commented
Ci can be freezed very rarely. So I written issue about it - https://github.com/ostis-ai/sc-machine/issues/171

2022-09-27 17:47 UTC, merged