Add main docs file
ostis-ai/sc-machine pull request #188
Opened 2022-10-24 20:09 UTC by VasKho

* [x] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [x] Update documentation

2023-01-04 13:42 UTC, NikitaZotov reviewed
Good. Please, add changes message into changelog

2023-01-04 16:58 UTC, KovalM requested changes
1. Add info about build documentation in README.
2. We have no info about need to init submodule in our build documentation

2023-01-05 12:57 UTC, NikitaZotov approved these changes

2023-01-06 09:09 UTC, KovalM approved these changes

2023-01-09 13:17 UTC, merged