[tools][server] Add output structure to sc-server create elements by SCs endpoint
ostis-ai/sc-machine pull request #208
Opened 2023-01-03 16:34 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [ ] Update documentation

2023-01-03 19:03 UTC, KovalM requested changes

2023-01-03 19:03 UTC, KovalM commented on sc-tools/sc-server/tests/api/units/test_base.cpp
> +  EXPECT_TRUE(m_ctx->HelperCheckEdge(structure, edge, ScType::EdgeAccessConstPosPerm));
Add check that five-elements-constructions of system idtf also added structure. Now, it's blocked by https://github.com/ostis-ai/sc-machine/issues/207

2023-01-24 15:09 UTC, SHtress requested changes

2023-01-24 15:09 UTC, SHtress commented on sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-action/sc_memory_create_elements_by_scs_json_action.hpp
> +        outputStructure = ScAddr(atom["outputStructure"].get<size_t>());
```suggestion
        outputStructure = ScAddr(atom["output_structure"].get<size_t>());
```

2023-01-25 16:50 UTC, KovalM approved these changes

2023-01-26 07:09 UTC, SHtress approved these changes

2023-01-26 08:05 UTC, merged