Feature/add result structure
ostis-ai/sc-machine pull request #210
Opened 2023-01-04 13:30 UTC by smousy

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [ ] Update documentation

2023-01-04 16:48 UTC, KovalM requested changes

2023-01-04 16:48 UTC, KovalM commented on sc-tools/sc-builder/src/scs_translator.cpp
> +      if (!scs.GenerateBySCsText(data, params.m_outputStructure))
I think we can leave only this "if". We can call scs.GenerateBySCsText(data, params.m_outputStructure), this method will ignore second param if it's not valid

2023-01-05 10:32 UTC, NikitaZotov requested changes

2023-01-06 13:44 UTC, NikitaZotov requested changes

2023-01-06 13:44 UTC, NikitaZotov commented on sc-tools/sc-config-utils/sc_builder_config.hpp
> +                                                      : DEFAULT_RESULT_STRUCTURE_MAIN_IDT;
```suggestion
                                                      : DEFAULT_RESULT_STRUCTURE_MAIN_IDTF;
```

2023-01-06 13:44 UTC, NikitaZotov commented on sc-tools/sc-config-utils/sc_builder_config.hpp
> +  }
```suggestion
  ~ScBuilderConfig() = default;
```

2023-01-06 13:44 UTC, NikitaZotov commented on sc-tools/sc-config-utils/sc_memory_config.hpp
> +    m_memoryParams.clear = m_params.count("clear") ? (m_params.at("clear") == "true" ? SC_TRUE : SC_FALSE) : SC_FALSE;
Add info about this fix into changelog

2023-01-06 13:44 UTC, NikitaZotov commented on sc-tools/sc-builder/tests/units/test_base.cpp
> +    sc_memory_params scMemoryParams = memoryConfig.GetParams();
```suggestion
    sc_memory_params const scMemoryParams = memoryConfig.GetParams();
```

2023-01-06 13:44 UTC, NikitaZotov commented on docs/changelog.md
> +- Add output structure builder feature to config
Move it into the begin of this section, please. The first messages of each section show what was changed last, and the last messages show what was done the firstly

2023-01-06 15:22 UTC, KovalM approved these changes

2023-01-06 15:41 UTC, NikitaZotov approved these changes

2023-01-10 12:29 UTC, merged