[test] Add test to resolve node with russian idtf
ostis-ai/sc-machine pull request #213
Opened 2023-01-05 10:05 UTC by smousy

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation
Fixed #127

2023-01-05 10:18 UTC, KovalM requested changes
We should forbid to use Cyrillic for system idtf

2023-01-06 13:47 UTC, KovalM requested changes

2023-01-06 13:47 UTC, KovalM commented on sc-memory/sc-core/sc_helper.c
> +  regcomp(&regex, "([a-z]|[A-Z]|'_'|'.'|[0-9])+", REG_EXTENDED);
Move regex to constants. And move similar code to function or macros

2023-01-06 15:07 UTC, KovalM approved these changes

2023-01-06 15:24 UTC, NikitaZotov reviewed
Add changelog message

2023-01-06 15:28 UTC, NikitaZotov commented on sc-memory/sc-core/sc_helper.c
> +sc_result sc_helper_check_system_identifier(const sc_char * data)
Please, add function definition to header `sc-helper.h`

2023-01-06 15:38 UTC, NikitaZotov approved these changes

2023-01-09 11:21 UTC, merged