Add init keynodes to result structure
ostis-ai/sc-machine pull request #219
Opened 2023-01-11 11:33 UTC by SHtress

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentatio[Trello Card](https://trello.com/c/Bde8S4G9)

2023-01-12 13:56 UTC, NikitaZotov requested changes

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
> +    for (ScAddrVector keynodes : keynodeVectors)
```suggestion
    for (ScAddrVector const & keynodes : keynodeVectors)
```

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
> +      for (ScAddr keynodeAddr : keynodes)
```suggestion
      for (ScAddr const & keynodeAddr : keynodes)
```

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
> +  std::vector<ScAddrVector> const & keynodeVectors = {keynodesAddrs, resultCodes, binaryTypes};
```suggestion
  std::vector<ScAddrVector &> const & keynodeVectors = {keynodesAddrs, resultCodes, binaryTypes};
```

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
>      result = result && resAddr.IsValid();
```suggestion
    result &= resAddr.IsValid();
```
else you create tempory object

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
>      result = result && resAddr.IsValid();
Check it everywhere and correct

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
> +      if (result && resultStructValid)
So

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
> +    if (resultStructValid)
Use braced if instead of such it

2023-01-12 13:56 UTC, NikitaZotov commented on sc-memory/tests/sc-memory/common/sc-memory.cpp
> +  for (ScAddrVector const & keynodes : keynodesVectors)
Divide this cycle into lambdas or functions to improve code readability

2023-01-16 15:33 UTC, NikitaZotov requested changes

2023-01-16 15:33 UTC, NikitaZotov commented on sc-memory/tests/sc-memory/_test/sc_test.hpp
> +};
```suggestion
};

```

2023-01-16 15:33 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
>        result = false;
Check it logic please

2023-01-16 15:33 UTC, NikitaZotov commented on sc-memory/tests/sc-memory/common/sc-memory.cpp
> +  ScIterator3Ptr it3 = m_ctx->Iterator3(keynodeAddr, ScType::EdgeAccessConstPosPerm, otherKeynodeAddr);
```suggestion
  ScIterator3Ptr const it3 = m_ctx->Iterator3(keynodeAddr, ScType::EdgeAccessConstPosPerm, otherKeynodeAddr);
```

2023-01-17 06:23 UTC, smousy requested changes

2023-01-17 06:23 UTC, smousy commented on config/sc-machine.ini
> +result_structure_upload = true
maybe duplicated is not a good idea? What if memory result_structure_system_idtf != builder  result_structure_system_idtf ? should stay parameters in builder section or different names for parameters in memory section

2023-01-17 19:43 UTC, KovalM requested changes

2023-01-17 19:43 UTC, KovalM commented on sc-memory/tests/sc-memory/common/sc-memory.cpp
> +TEST_F(ScMemoryTestWithResultStruct, TestResultStruct)
This test should also check that link with system idtf of keynode, edges to this links, also was added to result.

test_keynode
 => [test_keynode]
  ^
  |
 nrel_system_identificator

2023-01-17 19:43 UTC, KovalM commented on sc-memory/sc-memory/sc_memory.cpp
> +  ScKeynodes::Init(false, params.result_structure_upload ? params.result_structure_system_idtf : (sc_char *)null_ptr);
For discuss: what about keynodes from applications

2023-01-19 09:27 UTC, KovalM approved these changes

2023-01-19 13:06 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory_params.c
> +  params->result_structure_system_idtf = (sc_char const *)null_ptr;
Change result_structure by init_memory_generated_structure

2023-01-21 13:34 UTC, NikitaZotov requested changes

2023-01-21 13:34 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_keynodes.cpp
> +      if (resultStructValid && binaryTypeEdge.IsValid())
```suggestion
      if (initMemoryGeneratedStructureValid && binaryTypeEdge.IsValid())
```

2023-01-21 13:34 UTC, NikitaZotov commented on sc-tools/sc-builder/src/main.cpp
> +  memoryParams.insert(
Fix namings here

2023-01-24 11:45 UTC, NikitaZotov approved these changes

2023-01-24 14:48 UTC, merged