Erase elements agent
ostis-ai/sc-machine pull request #220
Opened 2023-01-12 11:30 UTC by Vikort

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-01-12 11:42 UTC, Vikort commented
Example agent input:
![EraseElementsAgentInput1](https://user-images.githubusercontent.com/43759605/212057744-50b7dfa9-7218-41fe-9c5d-625e0dd4aca4.png)
Example agent output:
![EraselementsAgentOutput1](https://user-images.githubusercontent.com/43759605/212057754-574f3924-de17-4bdd-9f2e-7bd7db278ad9.png)

2023-01-16 14:29 UTC, MikhailSadovsky approved these changes

2023-01-16 15:26 UTC, NikitaZotov requested changes

2023-01-16 15:26 UTC, NikitaZotov commented on docs/changelog.md
> +- Add EraseElementsAgent
```suggestion
- EraseElementsAgent
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/agents/EraseElementsAgent.cpp
> +  ScIterator3Ptr iterator3 =
```suggestion
  ScIterator3Ptr const iterator3 =
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/agents/EraseElementsAgent.cpp
> +    ScAddr element = iterator3->Get(2);
```suggestion
    ScAddr const & element = iterator3->Get(2);
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/agents/EraseElementsAgent.cpp
> +    if (!m_memoryCtx.HelperCheckEdge(
Use braced if constructions, please

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/agents/EraseElementsAgent.cpp
> +      elementsToErase.push_back(element);
Remove elements here instead of pushing to vector and remove after

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/agents/EraseElementsAgent.cpp
> +  ScAddr answerSet = m_memoryCtx.CreateNode(ScType::NodeConst);
```suggestion
  ScAddr const & answerSet = m_memoryCtx.CreateNode(ScType::NodeConst);
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/agents/EraseElementsAgent.cpp
> +  size_t answerSize = answerElements.size();
```suggestion
  size_t const answerSize = answerElements.size();
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/agents/EraseElementsAgent.cpp
> +    ScAddr edge = m_memoryCtx.CreateEdge(ScType::EdgeAccessConstPosPerm, answerSet, answerElements[i]);
```suggestion
    ScAddr const & edge = m_memoryCtx.CreateEdge(ScType::EdgeAccessConstPosPerm, answerSet, answerElements[i]);
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/tests/sc-agents/erase_elements_agent_test.cpp
> +  ScAddr erasableElementsSet = context.CreateNode(ScType::NodeConst);
```suggestion
  ScAddr const & erasableElementsSet = context.CreateNode(ScType::NodeConst);
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/tests/sc-agents/erase_elements_agent_test.cpp
> +  ScAddr edge = context.CreateEdge(ScType::EdgeAccessConstPosPerm, testActionNode, erasableElementsSet);
```suggestion
  ScAddr const & edge = context.CreateEdge(ScType::EdgeAccessConstPosPerm, testActionNode, erasableElementsSet);
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/tests/sc-agents/erase_elements_agent_test.cpp
> +  ScAddr testActionNode = context.CreateNode(ScType::NodeConst);
```suggestion
  ScAddr const & testActionNode = context.CreateNode(ScType::NodeConst);
```

2023-01-16 15:26 UTC, NikitaZotov commented on sc-kpm/tests/sc-agents/erase_elements_agent_test.cpp
> +  ScAddr edge = context.CreateEdge(ScType::EdgeAccessConstPosPerm, testActionNode, erasableElementsSet);
Check it everywhere please

2023-01-19 17:24 UTC, KovalM requested changes
We need to discuss about this agent. We plan to move sc-agents-common from sc-machine to separate component. Also, we already have garbage agent in sc-machine in C. And better way to upgrade it.

Also, we need to discuss about unerasable_elements keynode

2023-02-01 08:25 UTC, KovalM commented
It was decided to modify the garbage agent  in C that already exist in project

2023-02-01 08:25 UTC, closed without merging