[memory][scs-helper] Add system identifiers to output structure
ostis-ai/sc-machine pull request #222
Opened 2023-01-16 16:23 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-01-17 08:37 UTC, SHtress commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +      auto const trgAddrResult = ResolveElement(trg);
Why auto?

2023-01-17 08:37 UTC, SHtress commented on sc-memory/sc-memory/sc_scs_helper.cpp
> -      SC_ASSERT(srcAddr.IsValid() && trgAddr.IsValid(), ());
Why remove addr validation?

2023-01-17 20:02 UTC, KovalM requested changes

2023-01-17 20:02 UTC, KovalM commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +  ScAddrVector SetSystemIdtf(std::string const & idtf, ScAddr const & addr)
After this change, we will have two ways of system idtf generation: this and m_ctx->HelperSetSystemIdtf. As result, we should support this two ways.

I think, we should leave only one way

2023-01-24 07:54 UTC, smousy requested changes

2023-01-24 07:54 UTC, smousy commented on sc-memory/sc-memory/sc_scs_helper.cpp
> +    SC_ASSERT(m_kNrelSysIdtf.IsValid(), ("Keynode `nrel_system_identifier` is not valid"));
Why you add assert instead of exception?

2023-01-25 10:24 UTC, KovalM approved these changes

2023-01-25 12:42 UTC, SHtress approved these changes

2023-01-25 14:25 UTC, SHtress approved these changes

2023-01-25 14:39 UTC, KovalM requested changes

2023-01-25 14:39 UTC, KovalM commented on sc-memory/sc-memory/sc_memory.cpp
> +bool ScMemoryContext::HelperResolveSystemIdtf(
Let's leave single implementation of HelperResolveSystemIdtf

2023-01-25 14:42 UTC, smousy approved these changes

2023-01-25 15:39 UTC, KovalM approved these changes

2023-01-25 15:51 UTC, merged