[tools][codegen][sc-memory] Add keynodes idtfs to structure
ostis-ai/sc-machine pull request #229
Opened 2023-01-25 14:18 UTC by SHtress

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-01-26 09:47 UTC, NikitaZotov requested changes

2023-01-26 09:47 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_defines.hpp
> +    static bool InitGlobal(ScAddr const & outputStructure = ScAddr::Empty) \
Add info about this method, please

2023-01-26 09:47 UTC, NikitaZotov commented on sc-memory/sc-memory/sc_object.hpp
> +  virtual bool _InitInternal(ScAddr const & outputStructure = ScAddr::Empty) = 0;
Extend info about this method, please

2023-01-26 09:47 UTC, NikitaZotov commented on docs/changelog.md
> +- Insert sc-keynodes and their system identifiers in global knowledge base during sc-memory initiation
Also point that you fixed https://github.com/ostis-ai/sc-machine/issues/223

2023-01-26 13:18 UTC, NikitaZotov approved these changes

2023-01-30 12:02 UTC, smousy approved these changes

2023-01-30 12:28 UTC, KovalM approved these changes

2023-01-30 13:03 UTC, merged