[kpm] Update garbage deletion
ostis-ai/sc-machine pull request #233
Opened 2023-01-31 15:41 UTC by SHtress

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-02-14 07:58 UTC, NikitaZotov requested changes

2023-02-14 07:58 UTC, NikitaZotov commented on docs/sc-kpm/sc_core_agents.tex
> +        \scnrelfrom{зависимость}{Реализация sc-памяти}
```suggestion
        \begin{scnrelfromlist}{зависимости компонента}
                   \scnitem{Реализация sc-памяти}
        \end{scnrelfromlist}
```

2023-02-14 07:58 UTC, NikitaZotov commented on sc-kpm/sc-utils/utils_keynodes.c
> +const char keynode_question_erase_element_str[] = "question_erase_element";
Please, create issue to rename all questions to actions

2023-02-14 07:58 UTC, NikitaZotov commented on sc-kpm/tests/sc-utils/sc-utils.cpp
> +      sc_event_new(context, keynode_question_initiated, SC_EVENT_ADD_OUTPUT_ARC, 0, agent_garbage_delete, 0);
```suggestion
      sc_event_new(context, keynode_question_initiated, SC_EVENT_ADD_OUTPUT_ARC, null_ptr, agent_garbage_delete, null_ptr);
```

2023-02-14 07:58 UTC, NikitaZotov commented on sc-kpm/tests/sc-utils/sc-utils.cpp
> +      sc_event_new(context, keynode_question_initiated, SC_EVENT_ADD_OUTPUT_ARC, 0, agent_garbage_delete, 0);
Check it everywhere

2023-02-14 07:58 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory_ext.c
> +  char * init_func_type;
```suggestion
  sc_char * init_func_type;
```

2023-02-14 07:58 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory_ext.c
> +      if (g_module_symbol(mi->ptr, "sc_module_initialize_with_init_memory_generated_structure", (gpointer *)&func) ==
```suggestion
      if (g_module_symbol(mi->ptr, "sc_module_initialize_ext", (gpointer *)&func) ==
```

2023-02-14 07:58 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory_ext.c
> +    if (module->init_func_type == "sc_module_initialize_with_init_memory_generated_structure")
Compare strings in c with sc_str_cmp

2023-02-14 08:35 UTC, SHtress commented on docs/sc-kpm/sc_core_agents.tex
> +        \scntext{пояснение}{Текущая реализация агента осуществляет физическое удаление sc-элементов, принадлежавших входному множеству, из sc-памяти, если они не принадлежат согласованной части базы
Let's discuss format

2023-02-14 11:37 UTC, SHtress commented on sc-kpm/tests/sc-utils/sc-utils.cpp
> +      sc_event_new(context, keynode_question_initiated, SC_EVENT_ADD_OUTPUT_ARC, 0, agent_garbage_delete, 0);
Can't build after this changes

2023-02-24 18:25 UTC, MikhailSadovsky approved these changes

2023-02-27 07:23 UTC, NikitaZotov commented on docs/changelog.md
> +- Update garbage deletion agent logic, add check if element belongs to init memory structure
Add info about fixes and info about other changes

2023-02-27 07:48 UTC, NikitaZotov commented on docs/changelog.md
> +- Converting to string params from configs([248](https://github.com/ostis-ai/sc-machine/issues/248))
```suggestion
- Converting to string params from configs
```

2023-02-27 07:51 UTC, NikitaZotov approved these changes

2023-02-27 08:06 UTC, merged