[tools][memory] Lookup save and update memory state
ostis-ai/sc-machine pull request #253
Opened 2023-03-02 16:23 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-03-02 19:53 UTC, MikhailSadovsky commented on sc-tools/sc-server/tests/sc-server-test.ini
> +save_period = 4
Should we set these values?

2023-03-03 07:46 UTC, MikhailSadovsky approved these changes

2023-03-03 09:11 UTC, KovalM requested changes
Got error during testing in ostis-web-platform:
1. set save_period and update_period in config to 4 
2. build kb
3. run sc-server
4. run sc-web
5. open localhosts:8000
6. go to SCg mode
7. create node
8. name node as test_node
9. create relation result* from root node to test_node
10. translate created constructions to KB
11. Ask system what is test_node
12. wait for 4 seconds
13. close terminal with run sc-web
14. close terminal wit run sc-server
15. run sc-server
16. run sc-web
17. open localhost

Expected result: new node should be in semantic neighborhood of start element

Actual result: 
![image](https://user-images.githubusercontent.com/8680298/222679811-631a05a6-859c-4ce6-b1fa-728618c1b041.png)

2023-03-03 10:36 UTC, KovalM approved these changes

2023-03-03 11:17 UTC, merged