Update component manager branch
ostis-ai/sc-machine pull request #259
Opened 2023-04-06 19:20 UTC by SHtress

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation
Need to update component manager branch.

2023-04-06 20:43 UTC, smousy approved these changes

2023-04-06 20:45 UTC, smousy reviewed
Last commit shows me empty, is it ok?

2023-04-06 22:40 UTC, NikitaZotov requested changes
Commit history is broken

2023-04-07 11:26 UTC, SHtress commented
Fix empty commit.
Be more specific about problems in commit history.

2023-04-10 11:44 UTC, NikitaZotov approved these changes

2023-04-10 15:11 UTC, merged