Fix json translator
ostis-ai/sc-machine pull request #264
Opened 2023-04-13 14:32 UTC by SHtress

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-04-14 15:45 UTC, NikitaZotov requested changes

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +      mInputConstructionAddr,
```suggestion
      mStructureAddr,
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +  collectScElementsInfo();
```suggestion
  collectStructureElementsInfo();
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +    if (std::any_of(mFiltersList.cbegin(), mFiltersList.cend(), [begAddr](sc_addr const & modifier) {
```suggestion
    if (std::any_of(mFilterList.cbegin(), mFiltersList.cend(), [begAddr](sc_addr const & modifier) {
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +    sScElementInfo * elInfo = resolveElementInfo(it.first, it.second);
```suggestion
    ScStructureElementInfo * elInfo = resolveElementInfo(it.first, it.second);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +    sScElementInfo * begInfo = resolveElementInfo(begAddr);
```suggestion
    sScElementInfo * begInfo = resolveStructureElementInfo(begAddr);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +    elInfo->source = begInfo;
```suggestion
    elInfo->sourceInfo = begInfo;
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +    elInfo->target = endInfo;
```suggestion
    elInfo->targetInfo = endInfo;
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +    sScElementInfo * edgeInfo = mScElementsInfo[it.first];
```suggestion
    sScElementInfo * edgeInfo = mStructureElementsInfo[it.first];
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +      sScElementInfo::tScElementInfoList removableArcs;
```suggestion
      sScElementInfo::StructureElementInfoList removableArcs;
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +      elInfo->structKeyword = findStructKeyword(keynodes);
```suggestion
      elInfo->structKeyword = findStructureKeyword(keynodes);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +void uiSc2SCnJsonTranslator::json(sScElementInfo * elInfo, int level, bool isStruct, sc_json & result)
```suggestion
void uiSc2SCnJsonTranslator::parseScnJsonSentence(sScElementInfo * elInfo, int level, bool isStruct, sc_json & result)
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +  getBaseInfo(elInfo, result);
```suggestion
  getElementInfo(elInfo, result);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +  if (elInfo->type & sc_type_arc_mask)
Let's for each structure element type create alone method. Decompose this (json) method on atomic methods

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +      sc_stream * stream;
Content proccesing move to other method

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +  if (level < maxLevel || (elInfo->type & sc_type_node && elInfo->type & sc_type_node_tuple))
```suggestion
  if (level < maxLevel || (elInfo->type & sc_type_node & sc_type_node_tuple))
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +      getJsonOfLinkedNodes(resultChildren, level + 1, isStruct);
```suggestion
      parseLinkedNodesScnJson(resultChildren, level + 1, isStruct);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +      getChildrenByModifierAddr(elInfo, modifier, isStruct, resultChildren);
```suggestion
      parseChildrenScnJsonByModifier(elInfo, modifier, isStruct, resultChildren);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +void uiSc2SCnJsonTranslator::getChildren(sScElementInfo * elInfo, bool isStruct, sc_json & children)
```suggestion
void uiSc2SCnJsonTranslator::parseChildrenScnJson(sScElementInfo * elInfo, bool isStruct, sc_json & children)
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +  getChildrenByDirection(elInfo->outputArcs, scnTranslatorConstants::RIGHT.data(), isStruct, children);
```suggestion
  parseChildrenScnJsonByDirection(elInfo->outputArcs, scnTranslatorConstants::RIGHT.data(), isStruct, children);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +        (*result)[scnTranslatorConstants::ARCS.data()].push_back(child[scnTranslatorConstants::ARCS.data()][0]);
```suggestion
        (*result)[ScnJsonTranslatorConstants::ARCS.data()].push_back(child[scnTranslatorConstants::ARCS.data()][0]);
```

2023-04-14 15:45 UTC, NikitaZotov commented on sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c
> +  if (node->data_list != null_ptr && full_list->size < 100)
Remove it

2023-04-14 15:45 UTC, NikitaZotov commented on sc-memory/sc-core/sc-store/sc-fs-storage/sc_dictionary_fs_storage.c
> +  if (node->data_list != null_ptr && full_list->size < 100)
Remove it

2023-04-14 15:45 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +namespace scnTranslatorConstants
Let's name all type and methods names with `CamelCase`

2023-04-14 18:12 UTC, FallenChromium approved these changes
The linker fix looks good to me

2023-04-17 09:21 UTC, NikitaZotov approved these changes

2023-04-17 09:21 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.h
> +  StructureElementInfoList outputArcs;
```suggestion
  ScStructureElementInfoList outputArcs;
```

2023-04-17 09:21 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.h
> +  void GetElementInfo(ScStructureElementInfo * elInfo, sc_json & result);
```suggestion
  void ParseScElementInfo(ScStructureElementInfo * elInfo, sc_json & result);
```

2023-04-17 09:21 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.h
> +  void GetChild(ScStructureElementInfo * arcInfo, String const & direction, bool isStruct, sc_json & child);
```suggestion
  void ParseScnJsonChild(ScStructureElementInfo * arcInfo, String const & direction, bool isStruct, sc_json & child);
```

2023-04-17 09:21 UTC, NikitaZotov requested changes
Fix style

2023-04-17 13:03 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +                \begin{scnreltolist}{разбиение}
```suggestion
                \begin{scnrelfromlist}{разбиение}
```

2023-04-17 13:13 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +                            \scnitem{scn-json-arc}
```suggestion
                            \scnitem{scn-json-коннектор}
```

2023-04-17 13:14 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +                    \scnitem{scn-json-modifiers}
```suggestion
                    \scnitem{scn-json-модификатор}
```

2023-04-17 13:16 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +                        \begin{scnreltolist}{разбиение}
Включение

2023-04-24 17:08 UTC, NikitaZotov requested changes

2023-04-24 17:08 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +                                    \scnitem{scn-json-спецификация sc-коннекторов для заданного scn-json-модификатор}
```suggestion
                                    \scnitem{scn-json-спецификация sc-коннекторов для заданного scn-json-модификатора}
```

2023-04-24 17:08 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +        \scntext{пояснение}{формат в которой необходимо протранслировать, в данном случае формат scn (json)}
везде пересмотри

2023-04-24 17:08 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +  if (contentType.is_null())
Divide this condition into more atomic conditions

2023-04-24 17:08 UTC, NikitaZotov commented on sc-kpm/sc-ui/translators/uiSc2SCnJsonTranslator.cpp
> +  sc_json arc;
```suggestion
  ScJson arc;
```

2023-04-24 17:08 UTC, NikitaZotov commented on sc-kpm/tests/translators/ui-scn-json-translator.cpp
> +      return {};
```suggestion
      return ScAddr::Empty;
```

2023-04-24 17:08 UTC, NikitaZotov commented on sc-kpm/tests/translators/ui-scn-json-translator.cpp
> +      return {};
Recheck it everywhere

2023-04-27 07:50 UTC, NikitaZotov reviewed
I checked code by valgrind tool. There are no memory leaks.

2023-04-27 07:50 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +\scnheader{scn-json-modifier-arcs}
```suggestion
\scnheader{scn-json-спецификация sc-коннекторов, следующих за модификатором}
```

2023-04-27 07:50 UTC, NikitaZotov commented on docs/sc-kpm/sc_ui_scn_json_translator.tex
> +        \scntext{пояснение}{язык содержимого sc-ссылок и идентификаторов}
```suggestion
        \scntext{пояснение}{язык содержимого файлов ostis-системы}
```

2023-04-27 07:50 UTC, NikitaZotov commented on sc-kpm/tests/translators/test-structures/command_init_checks/init_ui_translator.scs
> +question_addr => nrel_answer: answer_addr;;
newline

2023-04-27 07:50 UTC, NikitaZotov commented on sc-kpm/tests/translators/test-structures/command_init_checks/command_init_no_format.scs
> +system_element -> (trans_cmd_addr <- ui_command_translate_from_sc);;
newline

2023-04-28 17:08 UTC, NikitaZotov commented
Clean history and merge it!

2023-04-28 17:08 UTC, NikitaZotov approved these changes

2023-04-29 10:03 UTC, merged