[refactor][tools][sc-server] Restruct logs in sc-server
ostis-ai/sc-machine pull request #298
Opened 2023-06-08 15:01 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-06-12 13:07 UTC, MksmOrlov requested changes
There is no `components`. Rename according to the Standard
![image](https://github.com/ostis-ai/sc-machine/assets/36566977/52495b4b-e359-437c-a4c6-c57ed3cb1971)
Make the last log message to understand that all is correct and ready to use

2023-06-14 12:36 UTC, NikitaZotov commented on sc-tools/sc-server/src/sc-server-impl/sc_server.cpp
There are library logs. We don't extend it, so I set such logs by default

2023-06-14 12:37 UTC, NikitaZotov commented on sc-tools/sc-server/src/sc-server-impl/sc_server.cpp
> +        m_instance->close(it, websocketpp::close::status::normal, "I finish work");
sc-server

2023-06-14 12:38 UTC, NikitaZotov commented
> There is no `components`. Rename according to the Standard ![image](https://user-images.githubusercontent.com/36566977/245152346-52495b4b-e359-437c-a4c6-c57ed3cb1971.png) Make the last log message to understand that all is correct and ready to use

there are no about how to write logs in sc-console in the Standart

2023-06-18 07:43 UTC, MksmOrlov commented on sc-tools/sc-server/src/sc-server-impl/sc_server.cpp
> +        m_instance->close(it, websocketpp::close::status::normal, "I finish work");
ну так write sc-server please

2023-06-18 07:44 UTC, MksmOrlov commented on sc-tools/sc-server/src/main.cpp
> +  catch (utils::ScException const & e)
What does your smile mean? Lets doiscuss

2023-06-18 07:45 UTC, MksmOrlov commented on sc-tools/sc-server/src/sc-server-impl/sc-memory-json/sc-memory-json-event/sc_memory_json_events_handler.hpp
> +      ScServerConnectionHandle const & hdl,
What does your smile mean? Lets doiscuss

2023-06-18 07:45 UTC, MksmOrlov commented on sc-tools/sc-server/src/sc-server-impl/sc_server.hpp
> +  explicit ScServer(std::string hostName, size_t port, sc_memory_params params);
What does your smile mean? Lets doiscuss

2023-06-18 07:49 UTC, MksmOrlov commented on sc-tools/sc-server/src/sc-server-impl/sc_server.cpp
> +  m_ioThread = std::thread(&ScServerCore::run, &*m_instance);
Why "Close input-output processing", not End? 
If you write _"start"_, write _"end"_, if you write "close" write "open"

2023-06-18 07:50 UTC, MksmOrlov commented
> > There is no `components`. Rename according to the Standard ![image](https://user-images.githubusercontent.com/36566977/245152346-52495b4b-e359-437c-a4c6-c57ed3cb1971.png) Make the last log message to understand that all is correct and ready to use
> 
> there are no about how to write logs in sc-console in the Standart

but there is _yes_ about what is a component

2023-06-18 07:50 UTC, MksmOrlov requested changes
Check unresolved

2023-06-19 09:08 UTC, NikitaZotov commented on sc-tools/sc-server/src/sc-server-impl/sc_server.hpp
> +  explicit ScServer(std::string hostName, size_t port, sc_memory_params params);
This const is surplus

2023-06-19 09:08 UTC, NikitaZotov commented on sc-tools/sc-server/src/main.cpp
> +  catch (utils::ScException const & e)
This renamings are surplus

2023-06-19 10:16 UTC, MksmOrlov approved these changes

2023-06-19 16:23 UTC, merged