[scripts][gwf2scs] Support gwf <0.4.0
ostis-ai/sc-machine pull request #333
Opened 2023-12-11 10:18 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2023-12-11 10:45 UTC, MksmOrlov requested changes

2023-12-11 10:45 UTC, MksmOrlov commented on sc-tools/sc-builder/tests/kb/test_gwf/gwf_0_3_2/connectors/1.gwf
Where are tests for old version gwf?

2023-12-14 09:18 UTC, NikitaZotov commented on sc-tools/sc-builder/tests/kb/test_gwf/gwf_0_3_2/connectors/1.gwf
Such test already exists. See RunStop test in ostis-ai/ostis-web-platform/sc-machine/sc-tools/sc-builder/tests/units/test_config.cpp

2023-12-14 14:31 UTC, MksmOrlov approved these changes

2023-12-14 16:10 UTC, merged