[tools][server] Implement user process authorization subscriptions
ostis-ai/sc-machine pull request #348
Opened 2023-12-22 21:21 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2024-01-05 15:07 UTC, KovalM requested changes

2024-01-06 15:57 UTC, KovalM requested changes

2024-01-06 15:57 UTC, KovalM commented on sc-memory/sc-core/sc-store/sc_iterator3.h
> + * example: while(sc_iterator_next(it)) { <your code> }
```suggestion
 * @example: while(sc_iterator_next_ext(it, result)) { <your code> }
```

2024-01-06 15:57 UTC, KovalM commented on sc-memory/sc-core/sc-store/sc_iterator5.h
> + * example: while(sc_iterator_next(it)) { <your code> }
```suggestion
 * @example: while(sc_iterator_next_ext(it, result)) { <your code> }
```

2024-01-10 18:09 UTC, NikitaZotov commented on sc-kpm/tests/sc-agents/sc-core-agents.cpp
> -  sc_memory_context_free(context);
Now, these tests use context from `ScMemoryTest`

2024-01-10 18:19 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory.c
> +  sc_char * my_self_system_idtf;
Sc-machine doesn't have this type. We use `sc_char *`.

2024-01-10 18:21 UTC, NikitaZotov commented on sc-memory/tests/sc-memory/common/sc-memory-context.cpp
It had already added.

2024-01-10 18:22 UTC, NikitaZotov commented on sc-tools/sc-server/tests/api/units/sc_server_test.hpp
> +    m_server = std::make_unique<ScServerImpl>("127.0.0.1", 8865, SC_TRUE, params);
Port and host are not specified in config. They are passed as options.

2024-01-10 18:31 UTC, NikitaZotov commented on sc-memory/sc-memory/kpm/sc_agent.cpp
> +ScAgent::ScAgent(ScAddr const & userAddr)
I think that anyone uses API of `ScAgent` directly. So I change code here instead of deprecate it.

2024-01-11 15:36 UTC, MksmOrlov requested changes

2024-01-11 15:36 UTC, MksmOrlov commented on sc-memory/tests/sc-memory/common/sc-memory-context.cpp
I don''t see it

2024-01-11 16:43 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory_context_manager.c
> +  sc_addr concept_action_subject_addr;             ///< sc_addr representing the concept node for action subjects.
Now it is `concept_authenticated_user_addr`. It is needed to say that user was authenticated

2024-01-11 16:46 UTC, NikitaZotov commented on sc-memory/tests/sc-memory/common/sc-memory-context.cpp
Oh, it is the test. We don't write lisence header in tests

2024-01-12 08:04 UTC, MksmOrlov commented on sc-memory/tests/sc-memory/common/sc-memory-context.cpp
why?

2024-01-12 17:18 UTC, MksmOrlov approved these changes

2024-01-14 12:28 UTC, KovalM requested changes

2024-01-14 12:28 UTC, KovalM commented on sc-memory/sc-core/sc_memory.h
> +_SC_EXTERN sc_memory_context * sc_memory_context_new_ext(sc_addr process_addr);
```suggestion
_SC_EXTERN sc_memory_context * sc_memory_context_new_ext(sc_addr user_addr);
```

2024-01-21 18:20 UTC, KovalM approved these changes

2024-01-22 18:43 UTC, merged