[memory][context] Local user access levels checks for complete actions in sc-structures
ostis-ai/sc-machine pull request #366
Opened 2024-02-06 22:19 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2024-02-12 15:04 UTC, MksmOrlov requested changes

2024-02-12 15:04 UTC, MksmOrlov commented on sc-memory/sc-memory/sc_memory.cpp
> +  ;
unused ;

2024-02-12 15:04 UTC, MksmOrlov commented on sc-memory/sc-memory/sc_memory.cpp
> +  return HelperSetSystemIdtf(sysIdtf, addr, quintuple);
verify system idtf not to duplicate

2024-02-13 22:30 UTC, KovalM requested changes

2024-02-16 15:33 UTC, NikitaZotov commented on sc-memory/sc-core/sc-store/sc_iterator3.c
> +  it->global_search = SC_FALSE;
It is not actual

2024-02-16 15:33 UTC, NikitaZotov commented on sc-memory/sc-core/sc-store/sc_iterator3.h
> +  sc_bool global_search;
It is not actual

2024-02-16 15:50 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory.c
> +  if (_sc_memory_context_check_local_and_global_access_levels(
I don't remember this. Let's discuss

2024-02-16 15:56 UTC, NikitaZotov commented on sc-memory/sc-core/sc_memory.c
> +          == SC_FALSE
We check that the provided begin sc-address is an sc-address of sc-structure that differs user access levels for sc-constructions in this sc-structure. 
1) If provided begin sc-address is an sc-address of such sc-structure and we want to generate access arc from it to some sc-element then we don't check the end sc-address. It is the case when user add something in your own sc-structure. He can do it if he has access levels for writing in this sc-structure.
2)  If provided begin sc-address is an sc-address of not such sc-structure then we check end sc-address.

2024-02-24 13:02 UTC, MksmOrlov approved these changes

2024-02-29 14:12 UTC, KovalM commented on sc-memory/sc-core/sc_memory.c
> +  if (_sc_memory_context_check_local_and_global_access_levels(
According our discuss, use 'permission' term

2024-02-29 14:13 UTC, KovalM requested changes
Use 'permission' term for access_levels

2024-02-29 15:25 UTC, SemSystemsInternal approved these changes

2024-02-29 17:32 UTC, merged