[scripts] Implement generalized build_cxx_project.sh; configure SC_BIN_PATH from scripts
ostis-ai/sc-machine pull request #372
Opened 2024-03-05 15:46 UTC by NikitaZotov

* [x] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [x] Update changelog
* [x] Update documentation

2024-03-06 16:20 UTC, MksmOrlov requested changes
![image](https://github.com/ostis-ai/sc-machine/assets/36566977/90421aef-0f13-4c9b-89c8-539ebfe2af1b)

2024-03-06 16:20 UTC, MksmOrlov commented
Install script doesn't install cmake?

2024-03-10 12:20 UTC, MakarenkoAI commented on scripts/set_vars.sh
change access right. script isnt executable

2024-03-10 12:23 UTC, MakarenkoAI commented on scripts/build-scripts/build_cxx_project.sh
![image](https://github.com/ostis-ai/sc-machine/assets/90891293/554eb955-72b7-43f0-a100-cb074c7734a8)
idk, maybe i must have run this from metasystem firstly or smth like that

2024-03-11 08:49 UTC, NikitaZotov commented on scripts/set_vars.sh
It is not for manual run

2024-03-11 08:55 UTC, NikitaZotov commented on scripts/build-scripts/build_cxx_project.sh
Fixed

2024-03-11 08:56 UTC, NikitaZotov commented
> Install script doesn't install cmake?

You ran not last version of scripts

2024-03-12 07:42 UTC, MksmOrlov approved these changes

2024-03-13 19:08 UTC, MakarenkoAI approved these changes

2024-03-16 08:43 UTC, merged