[kpm] Set system context for modules initialize
ostis-ai/sc-machine pull request #380
Opened 2024-04-03 21:14 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2024-04-04 08:44 UTC, KovalM approved these changes

2024-04-07 15:44 UTC, MksmOrlov requested changes
I dont like several identifiers.
- `s_memory_default_ctx` in c code
- `ms_globalContext` in c++ code
- `system contex` is what we call for it
What is the difference? Can we name it in the same way?

2024-04-09 11:31 UTC, NikitaZotov commented
> I dont like several identifiers.
> 
> * `s_memory_default_ctx` in c code
> * `ms_globalContext` in c++ code
> * `system context` is what we call for it
>   What is the difference? Can we name it in the same way?

It is not about this PR. `s_memory_default_ctx` is object in C, it satisfies the syntax of C. `ms_globalContext` is object in C++, is satisfies the syntax of C++. This objects has common class `system context`

2024-04-11 09:57 UTC, MksmOrlov commented
> > I dont like several identifiers.
> > 
> > * `s_memory_default_ctx` in c code
> > * `ms_globalContext` in c++ code
> > * `system context` is what we call for it
> >   What is the difference? Can we name it in the same way?
> 
> It is not about this PR. `s_memory_default_ctx` is object in C, it satisfies the syntax of C. `ms_globalContext` is object in C++, is satisfies the syntax of C++. This objects has common class `system context`

я не про синтакис. Я про смысл слов `default`, `global`, `system`. Почему бы везде не использовать слово `system`? Чем оно от глобала и дефолта отличается

2024-04-11 09:58 UTC, MksmOrlov requested changes
я не про синтакис. Я про смысл слов default, global, system. Почему бы везде не использовать слово system? Чем оно от глобала и дефолта отличается

2024-04-30 08:45 UTC, NikitaZotov commented
> я не про синтакис. Я про смысл слов default, global, system. Почему бы везде не использовать слово system? Чем оно от глобала и дефолта отличается

https://github.com/ostis-ai/sc-machine/issues/383

2024-04-30 08:48 UTC, MksmOrlov approved these changes

2024-05-22 16:28 UTC, merged