[memory][template] Implement load program object of sc-template into sc-memory
ostis-ai/sc-machine pull request #398
Opened 2024-07-30 10:09 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2024-07-30 17:10 UTC, FallenChromium commented on sc-memory/sc-memory/sc_template.hpp
> +   * @brief Loads the program object of program object of sc-template to a sc-template in sc-memory.
```suggestion
   * @brief Creates a structure in the sc-memory equivalent to the provided ScTemplate program object 
```

2024-08-01 10:36 UTC, MksmOrlov requested changes

2024-08-01 10:36 UTC, MksmOrlov commented on sc-memory/sc-memory/sc_template_load.cpp
> +protected:
public?

2024-08-17 16:44 UTC, MksmOrlov approved these changes

2024-08-17 17:57 UTC, merged