[WIP] Separate public and private headers
ostis-ai/sc-machine pull request #404
Opened 2024-08-16 13:42 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2024-10-04 14:05 UTC, KovalM approved these changes

2024-10-04 14:31 UTC, KovalM approved these changes

2024-10-07 06:16 UTC, kilativ-dotcom requested changes

2024-10-07 06:16 UTC, kilativ-dotcom commented on sc-memory/sc-memory/src/utils/sc_message.cpp
>  #include "../sc_platform.hpp"
is .. in path ok?

2024-10-07 06:54 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/src/GenerationUtils.cpp
> +#include "sc-agents-common/utils/CommonUtils.hpp"
What do you mean by different order?

2024-10-07 06:56 UTC, NikitaZotov commented on sc-memory/sc-core/src/sc-store/sc-base/sc_monitor_private.h
> +  sc_uint32 active_writer;   // Flag to indicate if a writer is writing
Doesn't make any difference, there will still be structure alignment

2024-10-07 06:57 UTC, NikitaZotov commented on sc-memory/sc-core/src/sc-store/sc_storage.h
> +void sc_storage_end_new_process();
No, I didn't change anything in the code, I just moved these methods around

2024-10-07 07:55 UTC, kilativ-dotcom commented on sc-kpm/sc-agents-common/src/GenerationUtils.cpp
> +#include "sc-agents-common/utils/CommonUtils.hpp"
now utils are splitted by algorithm and not in alphabetical order

2024-10-07 07:57 UTC, kilativ-dotcom commented on sc-kpm/sc-common/include/sc-common/sc_utils.h
>   * action_finished set.
```suggestion
```

2024-10-07 07:57 UTC, kilativ-dotcom commented on sc-memory/sc-core/src/sc-store/sc_storage.h
> +void sc_storage_end_new_process();
but they are in src folder and it is private

2024-10-07 07:58 UTC, NikitaZotov commented on sc-kpm/sc-agents-common/src/GenerationUtils.cpp
> +#include "sc-agents-common/utils/CommonUtils.hpp"
Alphabetical order is optional

2024-10-07 08:00 UTC, kilativ-dotcom requested changes

2024-10-07 08:00 UTC, kilativ-dotcom commented on sc-memory/sc-memory/src/utils/sc_signal_handler.cpp
> +#include "sc_platform.hpp"
sc-memory before sc_platform?

2024-10-07 08:00 UTC, NikitaZotov commented on sc-memory/sc-core/src/sc-store/sc_storage.h
> +void sc_storage_end_new_process();
Yes, they are private. They don't have to be open, they reveal the features of the sc-memory

2024-10-07 08:01 UTC, NikitaZotov commented on sc-memory/sc-memory/src/utils/sc_signal_handler.cpp
> +#include "sc_platform.hpp"
It is in src

2024-10-07 09:08 UTC, kilativ-dotcom commented on sc-kpm/sc-agents-common/src/GenerationUtils.cpp
> +#include "sc-agents-common/utils/CommonUtils.hpp"
won't you unsplit utils includes?

2024-10-07 10:12 UTC, kilativ-dotcom approved these changes
looks ok :+1:

2024-10-07 10:36 UTC, merged