[tools][builder][tests] Revert removing build group from config
ostis-ai/sc-machine pull request #433
Opened 2024-11-11 15:15 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/CONTRIBUTING.md)
* [ ] Update changelog
* [ ] Update documentation

2024-11-11 21:40 UTC, KovalM approved these changes

2024-11-12 14:00 UTC, kilativ-dotcom requested changes

2024-11-12 14:43 UTC, NikitaZotov commented on sc-tools/sc-machine-runner/src/sc_machine_runner.cpp
If you use this config, yes, but in general it is not necessary

2024-11-12 14:47 UTC, kilativ-dotcom commented on sc-tools/sc-builder/src/sc_builder_runner.cpp
> +      << "  --config|-c <config-name>.ini           Provide a path to configuration file that can set both input and "
```suggestion
      << "  --config|-c <config-name>.ini           Provide a path to configuration file that can set any of input or "
```

2024-11-13 14:32 UTC, kilativ-dotcom commented on sc-tools/sc-builder/src/sc_builder_runner.cpp
what do you think about updating documentation?

2024-11-15 07:22 UTC, kilativ-dotcom approved these changes

2024-11-15 08:23 UTC, merged