Add users auth
ostis-ai/sc-machine pull request #52
Opened 2022-05-19 13:56 UTC by SHtress

Changes from #7.

2022-05-19 15:48 UTC, AlexandrZagorskiy requested changes

2022-05-19 15:48 UTC, AlexandrZagorskiy commented on sc-kpm/sc-python/services/http_api/auth/__init__.py
> +__all__=['config','validators', 'constants']
space

2022-05-19 15:48 UTC, AlexandrZagorskiy commented on sc-kpm/sc-python/services/http_api/auth/config.py
> +    cnt.AUTH_FLAG: False,
remove it

2022-05-19 15:48 UTC, AlexandrZagorskiy commented on sc-kpm/sc-python/services/http_api/auth/constants.py
> +AUTH_FLAG = 'auth_flag'
remove it too

2022-05-19 15:48 UTC, AlexandrZagorskiy commented on sc-kpm/sc-python/services/http_api/http_api.py
> +            if "option(AUTH_ENABLED ON)" in file.read():
move to config

2022-05-19 15:48 UTC, AlexandrZagorskiy commented on .gitignore
> -.cache
return it

2022-05-19 16:16 UTC, AlexandrZagorskiy approved these changes

2022-05-20 19:10 UTC, NikitaZotov requested changes

2022-05-20 19:10 UTC, NikitaZotov commented on sc-kpm/sc-python/services/http_api/http_api.py
> +    path = os.path.join(Path(__file__).parent.parent.parent.parent.parent, "CMakeLists.txt")
Can we avoid relative path scheme using in code?

2022-05-20 19:10 UTC, NikitaZotov commented on sc-kpm/sc-python/services/http_api/http_api.py
> +                return False
```suggestion
            return params[cnt.AUTH_FLAG_STRING] in file.read():
```

2022-06-12 19:37 UTC, KovalM commented
Authentication will be rewrited for new sc-server implementation from #62

2022-06-12 19:37 UTC, closed without merging