[WIP][docs] Add docs in latex format from OSTIS Standart
ostis-ai/sc-machine pull request #73
Opened 2022-06-21 08:32 UTC by NikitaZotov

* [ ] Read PR [documentation](https://github.com/ostis-ai/sc-machine/blob/main/docs/dev/pr.md/)
* [ ] Update changelog
* [ ] Update documentation

This PR depends on #72.

2022-06-27 08:34 UTC, MikhailSadovsky requested changes

2022-06-27 08:34 UTC, MikhailSadovsky commented on docs/sc-network/sc_network.tex
> +\scnrelfromlist{компонент программной системы}{РРеализация подсистемы взаимодействия с внешней средой с использованием протоколов на основе формата JSON}
```suggestion
\scnrelfromlist{компонент программной системы}{Реализация подсистемы взаимодействия с внешней средой с использованием протоколов на основе формата JSON}
```

2022-06-27 08:34 UTC, MikhailSadovsky commented on docs/sc-control/sc_lock.tex
> +\scnrelfrom{смотрите}{\nameref{sd_agents}}
Ссылка не отображается в итоговом pdf-документе

2022-06-27 10:07 UTC, MikhailSadovsky approved these changes

2022-06-27 12:42 UTC, KovalM approved these changes

2022-06-30 13:30 UTC, MksmOrlov requested changes
remove docs/sc-memory/sc-storage/images/sc_storage.pdf

2022-07-01 07:37 UTC, NikitaZotov commented
> remove docs/sc-memory/sc-storage/images/sc_storage.pdf

It is an image. It is needed

2022-07-01 08:00 UTC, MksmOrlov approved these changes

2022-07-01 08:00 UTC, merged