Clang format
ostis-ai/sc-machine pull request #9
Opened 2022-03-12 08:39 UTC by Vikort

Moved [pr](https://github.com/ostis-dev/sc-machine/pull/402)

2022-03-24 10:31 UTC, KovalM requested changes
Add check formatting to CI, script for only check formatting. Look to source PR, this changes are presented there

2022-04-01 17:55 UTC, KovalM requested changes
1. Add information about using code check to docs
2. Add setup pre-push hooks for code check. Add to docs info about install hooks

2022-04-04 12:24 UTC, KovalM approved these changes

2022-04-04 17:21 UTC, FallenChromium requested changes
I see a major problem with this approach:
```shell
cd build
cmake ..
make
```
First, it changes the current directory which is undesirable. Second, it relies on `make` rather than `CMake` only, so if we're going to switch the build system someday (say `cmake -G Ninja`), our docs will be obsolete. I have a proposal: let's make this build command a standard:
```
cmake -B build
cmake --build build
```
It's shorter, only relies on CMake and it doesn't do the `cd`. If we'll adopt this approach in this PR, I'll make another one to redact it in the remaining places. I am not asking about this out of purely aesthetics reasons, look at what happened on my machine, for example:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/43214067/161595852-b3fb4778-5f74-4c03-a769-9d2afb829952.png">
I already have a build folder, but that shouldn't be a problem! If the script just used `build` as a target directory through cmake, rather than trying to create it manually, that would've passed.
I've also sent some minor notes about the documentation, but other than the problem stated above and docs changes, it looks good to me! The formatting rules themselves are a subject of discussion, personally I don't like how it looks, but it's very subjective so I'm not going to bring this up unless someone else wants to elaborate on the topic.

2022-04-04 17:21 UTC, FallenChromium commented on scripts/ci/check-formatting.sh
> +popd
```suggestion
cmake -B build -DSC_CLANG_FORMAT_CODE=ON
cmake --build build --target clangformat_check
```
To fix the potential issue when `build` folder already exists

2022-04-05 10:04 UTC, FallenChromium approved these changes
Looks good to me! We could get rid of other `pushd`/`popd` or `cd`/`cd ..` logic too while we're at it, but it's unnecessary to do it in this PR.

2022-04-05 10:20 UTC, merged